import re

tgt_line = """
J’ai quarante-six ans, je m’appelle Florent-Claude Labrouste et je déteste mon prénom, je crois qu’il tient son origine de deux membres de ma famille que mon père et ma mère souhaitaient, chacun de leur côté, honorer ; c’est d’autant plus regrettable que je n’ai par ailleurs rien à reprocher à mes parents, ils furent à tous égards d’excellents parents, ils firent de leur mieux pour me donner les armes nécessaires dans la lutte pour la vie, et si j’ai finalement échoué, si ma vie se termine dans la tristesse et la souffrance, je ne peux pas les en incriminer, mais plutôt un regrettable enchaînement de circonstances sur lequel j’aurai l’occasion de revenir – et qui constitue même, à vrai dire, l’objet de ce livre – je n’ai quoi qu’il en soit rien à reprocher à mes parents mis à part ce minime, ce fâcheux mais minime épisode du prénom, non seulement je trouve la combinaison Florent-Claude ridicule, mais ses éléments en eux-mêmes me déplaisent, en somme je considère mon prénom comme entièrement raté. Florent est trop doux, trop proche du féminin Florence, en un sens presque androgyne. Il ne correspond nullement à mon visage aux traits énergiques, sous certains angles brutaux, qui a souvent (par certaines femmes en tout cas) été considéré comme viril, mais pas du tout, vraiment pas du tout, comme le visage d’une pédale botticellienne. Quant à Claude n’en parlons pas, il me fait instantanément penser aux Claudettes, et l’image d’épouvante d’une vidéo vintage de Claude François repassée en boucle dans une soirée de vieux pédés me revient aussitôt, dès que j’entends prononcer ce prénom de Claude.

Changer de prénom n’est pas difficile, enfin je ne veux pas dire d’un point de vue administratif, presque rien n’est possible d’un point de vue administratif, l’administration a pour objectif de réduire vos possibilités de vie au maximum quand elle ne parvient pas tout simplement à les détruire, du point de vue de l’administration un bon administré est un administré mort, je parle plus simplement du point de vue de l’usage : il suffit de se présenter sous un prénom nouveau et au bout de quelques mois ou même de quelques semaines tout le monde s’y fait, il ne vient même plus à l’esprit des gens que vous ayez pu, par le passé, vous prénommer différemment. L’opération dans mon cas aurait été d’autant plus simple que mon second prénom, Pierre, correspondait parfaitement à l’image de fermeté et de virilité que j’aurais souhaité communiquer au monde. Mais je n’ai rien fait, j’ai continué à me laisser appeler par ce dégoûtant prénom de Florent-Claude, tout ce que j’ai obtenu de certaines femmes (de Camille et de Kate précisément, mais j’y reviendrai, j’y reviendrai), c’est qu’elles se limitent à Florent, de la société en général je n’ai rien obtenu, sur ce point comme sur presque tous les autres je me suis laissé ballotter par les circonstances, j’ai fait preuve de mon incapacité à reprendre ma vie en main, la virilité qui semblait se dégager de mon visage carré aux arêtes franches, de mes traits burinés n’était en réalité qu’un leurre, une arnaque pure et simple – dont, il est vrai, je n’étais pas responsable, Dieu avait disposé de moi mais je n’étais, je n’étais en réalité, je n’avais jamais été qu’une inconsistante lopette, et j’avais déjà quarante-six ans maintenant, je n’avais jamais été capable de contrôler ma propre vie, bref il paraissait très vraisemblable que la seconde partie de mon existence ne serait, à l’image de la première, qu’un flasque et douloureux effondrement."""

print(re.findall('\w+',tgt_line))
print(re.findall('\w',"---"))
test = re.findall('\w',"---")
print(len(test) == 0)